---
title: "Untitled"
author: "Alexa Davis"
date: "October 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
.libPaths("D:/R Library")
library(tidyverse)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
```




```{r}

makeupdata <- data.frame(type = rep(c("A","B","C"), each = 30), 
                         value = c(rnorm(30, mean=50, sd=5),                                          rnorm(30, mean=70, sd=3),                                               rnorm(30, mean=20, sd=8)))
                         
makeupdata %>% 
  group_by(type) %>% 
  summarise(meanVal= mean(value), 
            sdVal= sd(value), N = n(),
            seVal= sdVal/sqrt(N),
            CIhi= meanVal+1.96*seVal,
              CIlo=meanVal-1.96*seVal) -> madeUpsummary
```


```{r}
Adata<-
  ggplot()+ geom_bar(data=madeUpsummary, aes(x=type, y=meanVal, fill=c), colour="black", stat= "identity", fill="gray") + scale_y_continuous(breaks=seq(0,80, 10)) + theme_classic()+ labs(x=" ", y=" ") + theme(plot.title=element_text(hjust=0.5)) + geom_errorbar(data= madeUpsummary, aes(x=type, ymin=meanVal-seVal, ymax=meanVal+seVal), width=0.5)

DataB<- 
ggplot()+ geom_point(data= madeUpsummary, aes(x= type, y= meanVal, fill="gray")) + scale_y_continuous(breaks=seq(0,80, 10))+
   geom_errorbar(data=madeUpsummary, aes(x= type, ymin=meanVal-seVal, ymax=meanVal+seVal), 
                width=0.4, colour="black", alpha=0.9, size=0.3) + labs(x= " ",  y=" ") + theme_classic() + theme(legend.position = "none")


grid.arrange(Adata, DataB, ncol=2, left=textGrob("Values", rot=90, gp=gpar(cex=1.2)),top=textGrob("Graphs", gp=gpar(cex=1.2)), bottom=textGrob("Types", gp=gpar(cex=1.2)))-> Plots


ggsave(Plots, file ="Figs/plot.png", width=15, height=7)

```

